name: Copy PR Files to aisw-hud-data

on:
  workflow_dispatch:
    inputs:
      branchSubstring:
        description: 'Substring to search for in the PR branch name'
        required: true
        type: string

jobs:
  fetch-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch open PRs with matching branch name
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUBSTRING: ${{ github.event.inputs.branchSubstring }}
          REPO: ${{ github.repository }}
        run: |
          echo "Fetching open PRs for repo: $REPO"
          
          echo "PRs with branch name containing '$SUBSTRING':"

          gh pr list --state open --json number,headRefName \
            --repo "$REPO" \
            --jq ".[] | select(.headRefName | test(\"$SUBSTRING\")) | .number"
