name: Create File and Raise PR

on:
  push:
    branches:
      - main

jobs:
  create-file-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Clone target repository
        run: |
          gh repo clone akshkuma/repo2
          cd repo2
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create new file
        run: |
          echo "Hello, world!" > newfile.txt
          git add newfile.txt
          git commit -m "Add new file via GitHub Actions"
          git push origin main

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Automated PR: Add new file" --body "This PR adds a new file." --base main --head main --repo akshkuma/repo2
