name: Create File and Raise PR

on:
  push:
    branches:
      - main

jobs:
  create-file-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

     # - name: Install GitHub CLI
      #  run: |
       #   sudo apt update
        #  sudo apt install gh -y

      - name: Clone target repository
        env:
          GH_TOKEN: ${{ secrets.REPO2_ACCESS_TOKEN }}
        run: |
          git clone https://oauth2:${GH_TOKEN}@github.com/akshkuma/repo2.git
          cd repo2
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create new branch and add file
        run: |
          cd repo2
          git checkout -b new-feature-branch
          touch newfile.txt
          echo "Hello, world! $(date)"  >> newfile.txt
          git add newfile.txt
          git commit -m "Add new file via GitHub Actions"
          git push https://oauth2:${{ secrets.REPO2_ACCESS_TOKEN }}@github.com/akshkuma/repo2.git new-feature-branch

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.REPO2_ACCESS_TOKEN }}
        run: |
          cd repo2
          gh pr create --title "Automated PR: Add new file" --body "This PR adds a new file." --base main --head new-feature-branch
