name: test2

on: workflow_dispatch

jobs:
  clone-parent-target-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository aisw-hud
        uses: actions/checkout@v4

     # - name: Clone Private Repository using HTTPS
      #  env:
       #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: |
         # git clone https://oauth2:${GH_TOKEN}@github.com/akshkuma/repo2.git

      
      - name: Clone Private Repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           gh repo clone ROCm/aisw-hud-data
           ls -l aisw-hud-data
